# Generated by Django 3.2.12 on 2022-03-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulGuDong',
            fields=[
                ('dongCode', models.IntegerField(primary_key=True, serialize=False)),
                ('guName', models.CharField(max_length=50)),
                ('guCenterXPoint', models.FloatField()),
                ('guCenterYPoint', models.FloatField()),
                ('guXYPoint', models.TextField()),
                ('dongName', models.CharField(max_length=50)),
                ('dongCenterXPoint', models.FloatField()),
                ('dongCenterYPoint', models.FloatField()),
                ('dongXYPoint', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommercialArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercialCode', models.IntegerField()),
                ('commercialAreaName', models.CharField(max_length=50)),
                ('dongCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercialAreas', to='commercial_area.seoulgudong')),
            ],
        ),
    ]
