# Generated by Django 3.2.12 on 2022-04-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialarea',
            name='commercialCenterXPoint',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='commercialarea',
            name='commercialCenterYPoint',
            field=models.FloatField(default=0),
        ),
    ]
