# Generated by Django 3.2.12 on 2022-03-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoulDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
    ]
