# Generated by Django 3.2.12 on 2022-04-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialarearevenue',
            old_name='quaterRevenue',
            new_name='quarterRevenue',
        ),
    ]
