# Generated by Django 3.2.12 on 2022-04-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAreaApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartmentAvgPrice', models.IntegerField()),
                ('commercialArea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea')),
            ],
        ),
    ]
