# Generated by Django 3.2.12 on 2022-04-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0002_commercialareacompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAreaPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarterRevenue', models.BigIntegerField()),
                ('commercialArea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea')),
            ],
        ),
    ]
