# Generated by Django 3.2.12 on 2022-04-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0002_commercialareaapartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commercialareaapartment',
            old_name='commercialArea',
            new_name='commercialAreaCode',
        ),
    ]
