# Generated by Django 3.2.12 on 2022-04-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0002_rename_quaterrevenue_commercialarearevenue_quarterrevenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialareabackground',
            name='commercialArea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea'),
        ),
        migrations.AlterField(
            model_name='commercialareanumber',
            name='commercialArea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea'),
        ),
        migrations.AlterField(
            model_name='commercialareapeople',
            name='commercialArea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea'),
        ),
        migrations.AlterField(
            model_name='commercialarearevenue',
            name='commercialArea',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea'),
        ),
    ]
