# Generated by Django 3.2.12 on 2022-04-02 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0003_auto_20220403_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAreaBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankNumber', models.IntegerField()),
                ('hospitalNumber', models.IntegerField()),
                ('pharmacyNumber', models.IntegerField()),
                ('kindergardenNumber', models.IntegerField()),
                ('schoolNumber', models.IntegerField()),
                ('universityNumber', models.IntegerField()),
                ('departmentStoreNumber', models.IntegerField()),
                ('supermarketNumber', models.IntegerField()),
                ('theaterNumber', models.IntegerField()),
                ('hotelNumber', models.IntegerField()),
                ('airportNumber', models.IntegerField()),
                ('busTerminalNumber', models.IntegerField()),
                ('subwayNumber', models.IntegerField()),
                ('busStopNumber', models.IntegerField()),
                ('commercialArea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercial_area.commercialarea')),
            ],
        ),
    ]
