# Generated by Django 3.2.12 on 2022-04-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_area', '0006_alter_commercialareaapartment_apartmentavgprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialareaapartment',
            name='apartmentCount',
            field=models.BigIntegerField(default=0),
        ),
    ]
