# Generated by Django 3.2.12 on 2022-04-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeList',
            fields=[
                ('guName', models.CharField(max_length=10)),
                ('UrlId', models.IntegerField(primary_key=True, serialize=False)),
                ('cafeName', models.CharField(max_length=50)),
                ('cafeRate', models.FloatField()),
                ('reviewCount', models.CharField(max_length=10)),
                ('cafeAddress', models.CharField(max_length=255, null=True)),
                ('cafeHour', models.CharField(max_length=255, null=True)),
                ('cafeTel', models.CharField(max_length=20, null=True)),
                ('cafeHomepage', models.CharField(max_length=255, null=True)),
                ('cafeTag', models.CharField(max_length=255, null=True)),
                ('cafePhoto', models.TextField(null=True)),
                ('cafePoint', models.CharField(max_length=100)),
                ('commercialCode', models.ManyToManyField(related_name='commercialCode', to='commercial_area.CommercialArea')),
                ('dongCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dong_cafes', to='commercial_area.seoulgudong')),
            ],
        ),
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=255, null=True)),
                ('menuPrice', models.IntegerField(null=True)),
                ('UrlId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Url_id', to='cafes.cafelist')),
            ],
        ),
    ]
