# Generated by Django 3.2.12 on 2022-03-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelist',
            name='cafeHour',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
