# Generated by Django 3.2.12 on 2022-03-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafelist_cafehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafelist',
            name='cafeAddress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='cafeHomepage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='cafePhoto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cafelist',
            name='cafeTag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
