# Generated by Django 3.2.12 on 2022-04-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_auto_20220331_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=255, null=True)),
                ('menuPrice', models.IntegerField(null=True)),
                ('UrlId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Url_id', to='cafes.cafelist')),
            ],
        ),
    ]
